# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XA_c9Hbja7ALjmoTlhIZZ5-IyzwczX_C
"""

!pip install onnxruntime
!pip uninstall rembg -y
!pip install rembg
!uvicorn main:app --host 0.0.0.0 --port 8000

from fastapi import FastAPI, File, UploadFile
from PIL import Image, ImageEnhance
import io
from rembg import remove

app = FastAPI()

@app.post("/enhance-photo")
async def enhance_photo(file: UploadFile, brightness: float = 1.0, sharpness: float = 1.0):
    image = Image.open(file.file)

    # Adjust brightness
    enhancer = ImageEnhance.Brightness(image)
    image = enhancer.enhance(brightness)

    # Adjust sharpness
    enhancer = ImageEnhance.Sharpness(image)
    image = enhancer.enhance(sharpness)

    # Save image to bytes
    buf = io.BytesIO()
    image.save(buf, format="PNG")
    buf.seek(0)

    return {"message": "Photo enhanced successfully!"}

@app.post("/change-background")
async def change_background(file: UploadFile, new_bg: UploadFile = None):
    input_image = Image.open(file.file)
    input_image_bytes = io.BytesIO()
    input_image.save(input_image_bytes, format="PNG")
    input_image_bytes.seek(0)

    # Remove background
    output_image_bytes = remove(input_image_bytes.getvalue())
    output_image = Image.open(io.BytesIO(output_image_bytes))

    # Replace background if new_bg is provided
    if new_bg:
        bg_image = Image.open(new_bg.file).resize(output_image.size)
        output_image.paste(bg_image, (0, 0), output_image)

    # Save image to bytes
    buf = io.BytesIO()
    output_image.save(buf, format="PNG")
    buf.seek(0)

    return {"message": "Background changed successfully!"}

@app.get("/health")
def health():
    return {"status": "API is running"}