# -*- coding: utf-8 -*-
"""requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OVS6bGFScyViqZPw4VbencmoKZkYUK5G
"""

!pip install fastapi uvicorn pillow rembg onnxruntime
import fastapi
import uvicorn
import PIL # pillow package is imported as PIL
import rembg
import onnxruntime

with open("requirements.txt", "w") as f:
    f.write("fastapi\nuvicorn\npillow\nrembg\nonnxruntime")
!cat requirements.txt